medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      port: 5433
      dbname: telegram_db
      schema: raw   # schema where your telegram_messages table is
      threads: 1
